[package]
name = "robin_gb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.15.0"
futures = "0.3.30"
glam = "0.27.0"
num_enum = "0.7.2"
wgpu = "0.19.1"
winit = "0.29.10"
