name: CI

on:
  push:
    branches: [ "main", "ci-dev" ]
  pull_request:
    branches: [ "main", "ci-dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal # Required for rust-cache
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --verbose
    - uses: actions/checkout@v4
      with:
        path: test_roms
        repository: retrio/gb-test-roms
    - name: Run rom tests
      run: |
        printf "# Test Summary\n\n" >> $GITHUB_STEP_SUMMARY
        target/debug/ci_rom_test "test_roms/cpu_instrs/individual/01-special.gb" "test_roms/cpu_instrs/individual/02-interrupts.gb" "test_roms/cpu_instrs/individual/03-op sp,hl.gb" "test_roms/cpu_instrs/individual/04-op r,imm.gb" "test_roms/cpu_instrs/individual/05-op rp.gb" "test_roms/cpu_instrs/individual/06-ld r,r.gb" "test_roms/cpu_instrs/individual/07-jr,jp,call,ret,rst.gb" "test_roms/cpu_instrs/individual/08-misc instrs.gb" "test_roms/cpu_instrs/individual/09-op r,r.gb" "test_roms/cpu_instrs/individual/10-bit ops.gb" "test_roms/cpu_instrs/individual/11-op a,(hl).gb" >> $GITHUB_STEP_SUMMARY
    
