name: CI

on:
  push:
    branches: [ "main", "ci-dev" ]
  pull_request:
    branches: [ "main", "ci-dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal # Required for rust-cache
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --verbose
    - run: ls target/debug
    - uses: actions/checkout@v4
      with:
        repository: retrio/gb-test-roms
    - name: Run rom tests
      run: target/debug/ci_rom_test >> $GITHUB_STEP_SUMMARY
    
