name: Rust

on:
  push:
    branches: [ "main", "ci-dev" ]
  pull_request:
    branches: [ "main", "ci-dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal # Required for rust-cache
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v4
      with:
        path: target
        overwrite: true
